# Generated by Django 5.2.8 on 2025-11-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_price', models.FloatField()),
                ('product_time', models.TimeField()),
                ('quantity', models.IntegerField()),
                ('Company_Contact_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
